#!/usr/bin/env bash
# Install nginx on your web-01
apt-get -y update
apt-get -y install nginx

echo "<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
Hello World!
</body>
</html>
" > /var/www/html/index.html

