#!/usr/bin/env bash
# Configure your Nginx so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "<!DOCTYPE html>\
<html lang=\"en\">\
<head>\
	<meta charset=\"UTF-8\">\
	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\
	<title>Document</title>\
</head>\
<body>\
Hello World!\
</body>\
</html>\
" > /var/www/html/index.html

sed -i "/server_name _;/a\
location /redirect_me {\
  return 301 https://youtu.be/JrRwT6_H0xY;\
}" /etc/nginx/sites-available/default

service nginx restart
