#!/usr/bin/env bash
# Configure your Nginx so that /redirect_me is redirecting to another page.

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

echo "server {
  listen 80;
  listen [::]:80 default_server;


  root /var/www/html;
  index index.html;

  location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
