#!/usr/bin/env bash
# manages manage_my_process
case "$1" in
	start)
		./manage_my_process &
		pid=$(pgrep -f manage_my_process)
		echo "$pid" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;

	stop)
		pid=$(tail -n 1 < /var/run/my_process.pid)
		kill "$pid"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;

	restart)
		pid=$(tail -n 1 < /var/run/my_process.pid)
		kill "$pid"
		rm /var/run/my_process.pid

		./manage_my_process &
		pid=$(pgrep -f manage_my_process)
		echo "$pid" > /var/run/my_process.pid

		echo "manage_my_process restarted"
		;;

	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
