#!/usr/bin/env bash
# Write a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)


for file in *; do
  if [ -f "$file" ] && [[ "$file" != .* ]]; then
    filename=${file#*-}
    echo "$filename"
  fi
done
