#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file
sc="school"

if [ -e $sc ]
then
	echo "school file exists"
	if [ -s $sc ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f $sc ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
