#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2 localhost" >> /etc/new_hosts
echo "8.8.8.8 facebook.com" >> /etc/new_hosts

cat /etc/new_hosts >> /etc/hosts
rm /etc/new_hosts
